<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\EncryptHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="4.0.2" />
    <PackageReference Include="AutoWrapper.Core" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.23" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NLog" Version="5.0.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.3" />
    <PackageReference Include="OpenXmlPowerTools" Version="4.5.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.3.0" />
    <PackageReference Include="Swashbuckle.Core" Version="5.6.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataRooms.DataRepository\DataRooms.DataRepository.csproj" />
    <ProjectReference Include="..\LoggerModule\LoggerModule.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


</Project>
